tradução dos capítulos 1 a 4
agomesp/metodoFacil pull request #3
Opened 2022-01-11 17:11 UTC by paulorssalves

de grão em grão...

2022-01-11 22:24 UTC, agomesp requested changes

2022-01-11 22:24 UTC, agomesp commented on _chapters/01-introducao.md
> +Esse hackbook lhe permitirá parar de usar pornografia imediatamente, sem dor, e permanentemente. Sem força de vontade ou qualquer sensação de estar sendo privado ou fazendo um sacrifício. Ele não lhe
"nem te irá pressionar" ou "nem irá te pressionar"?

2022-01-11 23:13 UTC, paulorssalves commented on _chapters/01-introducao.md
> +Esse hackbook lhe permitirá parar de usar pornografia imediatamente, sem dor, e permanentemente. Sem força de vontade ou qualquer sensação de estar sendo privado ou fazendo um sacrifício. Ele não lhe
Acho que a segunda opção é melhor.

2022-01-12 00:31 UTC, agomesp approved these changes

2022-01-12 00:32 UTC, merged